import type { Metadata } from "next";

import "../globals.css";
import Navbar from "@/component/Navbar";

export const metadata: Metadata = {
  title: "Ai resume builder",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="min-h-screen">
        <header className="dark:text-white bg-slate-50 dark:bg-black text-black py-4 px-2 flex items-center justify-between sticky top-0 z-20">
          <Navbar />
        </header>
        <main className=" min-h-[80vh]">{children}</main>
      </body>
    </html>
  );
}
