import type { Metadata } from "next";

import "./globals.css";
import Link from "next/link";
import Image from "next/image";
import Footer from "@/component/Footer";
import Navbar from "@/component/Navbar";

export const metadata: Metadata = {
  title: "Ai resume builder",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="flex flex-col justify-between h-screen">
        <header className="dark:text-white bg-slate-50 dark:bg-black text-black py-4 px-2 flex items-center justify-between">
          <Navbar />
        </header>
        <main>{children}</main>
        <footer className="bg-white dark:bg-black/50 border-t border-slate-200 dark:border-slate-800">
          <Footer />
        </footer>
      </body>
    </html>
  );
}
