import type { Metadata } from "next";

import "./globals.css";
import Link from "next/link";
import Image from "next/image";

export const metadata: Metadata = {
  title: "Ai resume builder",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={``}>
        <header className="dark:text-white dark:bg-black bg-white text-black py-5 px-2 flex items-center justify-between">
          <h1 className="text-xl font-bold">ResumeCraft</h1>
          <nav className="hidden sm:flex">
            <ul className="list-none flex items-center gap-4 justify-between max-w-80">
              <Link
                className="text-lg font-medium text-slate-600 dark:text-slate-300 hover:text-white dark:hover:text-white transition-colors"
                href="/"
              >
                <li>Template</li>
              </Link>
              <Link
                className="text-lg font-medium text-slate-600 dark:text-slate-300 hover:text-white dark:hover:text-white transition-colors"
                href="/"
              >
                <li>Examples</li>
              </Link>
              <Link
                className="text-lg font-medium text-slate-600 dark:text-slate-300 hover:text-white dark:hover:text-white transition-colors"
                href="/"
              >
                <li>Pricing</li>
              </Link>
            </ul>
          </nav>
          <div className="flex items-center gap-4">
            <button
              type="button"
              className="py-1 px-2 bg-indigo-500 text-white rounded-md hover:bg-indigo-600 transition-colors focus:outline-none focus:ring-1 focus:ring-slate-100 focus:ring-offset-2 cursor-pointer"
            >
              Create My Resume
            </button>
            <Image
              src="/user.png"
              alt="profile pic"
              width={20}
              height={20}
              className="size-9"
            />
          </div>
        </header>
        <main>
          <section className="hero-bg bg-center">
            <div>
              <h1>Craft a Resume That Gets You Hired</h1>
              <p>
                Our Ai resume builder helps you create a professional resume in
                minutes. Stand out from the competition and land your dream job
              </p>
            </div>
          </section>
          {children}
        </main>
        <footer></footer>
      </body>
    </html>
  );
}
