"use client";
import type { Metadata } from "next";

import "../globals.css";
import Footer from "@/component/Footer";
import Navbar from "@/component/Navbar";

// export const metadata: Metadata = {
//   title: "Ai resume builder",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className=" min-h-screen relative">
        <header className="dark:text-white bg-slate-50 dark:bg-black text-black py-4 px-2 flex items-center justify-between sticky top-0 z-20">
          <Navbar />
        </header>
        <main className="pb-30 sm:pb-24">{children}</main>
        <footer className="bg-white dark:bg-black/50 border-t border-slate-200 dark:border-slate-800 absolute bottom-0 w-full">
          <Footer />
        </footer>
      </body>
    </html>
  );
}
